version: "3.9"

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp_local
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: password
      LOCAL_DEV_DOCKER: true
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DEBUG: 1
      WP_ALLOW_REPAIR: true
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: wp_local
      PHP_MEMORY_LIMIT: 512M
      APL_STRIPE_API_KEY: $APL_STRIPE_API_KEY
    volumes:
      - wordpress:/var/www/html
      - ./stripe-wp:/var/www/html/wp-content/plugins/stripe-wp
      - ./uploads-docker.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: exampleuser
        MYSQL_PASSWORD: examplepass
        UPLOAD_LIMIT: 300M
    restart: always


volumes:
  wordpress:
  db:
